### ISSUE TITLE
Error when run tmpl test

### ISSUE THREAD

**Issue by alexbaumgertner** [bem-archive/bem-bl-xjst#11]
Test repo https://github.com/alexbaumgertner/tmpl-spec-error

Ошибка в применении скомпилированных шаблонов возникает при запуске tmpl-тестов. Примеры собираются ок.

Требуется установка внутренней npm-библиотеки `islands-tools` (устанавливайте зависимости так: `npm i --registry=http://npm.yandex-team.ru`).

Возможно, это ошибка в https://github.com/enb-bem/enb-bem-tmpl-specs, но возможно и в компиляторе.

**Comment by arikon** [comment]
Подозрение на то, что шаблон падает на вызове `apply('csp')` в ситуации, когда шаблона для моды `csp` не существует.

https://github.com/alexbaumgertner/tmpl-spec-error/blob/master/desktop.blocks/test/test.bemhtml#L4

Если добавить шаблон `block test, csp: undefined`, то ошибка уходит.

**Comment by alexbaumgertner** [comment]
@arikon спасибо, да именно так и есть. При этом примеры собираются без ошибки.

**Comment by blond** [comment]
> При этом примеры собираются без ошибки.

Примеры ведь оборачиваются в `b-page`, который зависит от `i-bem__html`. А в тестах базовые шаблоны не доезжают.

Должен ли этот код работать без базовых шаблонов?

**Comment by alexbaumgertner** [comment]
@blond Вот пример без b-page: https://github.com/alexbaumgertner/tmpl-spec-error/blob/master/desktop.blocks/test/test.examples/10-test.bemjson.js
Он собирается ок
